# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    kernel.listener.json_request_transformer:
        class: AppBundle\Service\RequestTransformer\JsonRequestTransformer
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest}

    app.user_tracked_subscriber:
        class: AppBundle\Entity\Listeners\UserTrackedSubscriber
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.event_subscriber }

    app.controller.web.default:
        class: AppBundle\Controller\Web\DefaultController
        arguments: []

    app.roles_provider:
        class: AppBundle\Service\RolesProvider
        arguments: [ @security.token_storage, @security.authorization_checker]

    # -----------------
    # Admin Controllers
    # -----------------
    app.admin.user_controller:
        class: AppBundle\Controller\Admin\UserController
        arguments: ['@app.grid_managers.admin.user_manager', '@app.roles_provider', '@app.model.user_facade']

    # -----------------
    # Web Controllers
    # -----------------

    # -----------------
    # Model
    # -----------------
    app.model.user_facade:
        class: AppBundle\Model\UserFacade
        arguments: ['@doctrine.orm.entity_manager', '@app.notifications.user_create_mail']

    # -----------------
    # IS Grid managers
    # -----------------
    app.grid_managers.admin.user_manager:
        class: AppBundle\GridManagers\Admin\UserManager
        arguments: ['@doctrine.orm.entity_manager']

    # ---------------------------
    # Notifications
    # ---------------------------
    app.notifications.mailer:
        class: AppBundle\Service\Notification\Mailer
        arguments: ['@mailer', '@templating', '@translator']

    app.notifications.user_create_mail:
        class: AppBundle\Service\Notification\UserCreateMail
        arguments: ['@app.notifications.mailer', '%mailer_sender_mail%', '%mailer_sender_name%']

    # --------------------
    # Twig extensions
    # --------------------
    app.bool_extension:
        class: AppBundle\Twig\BoolExtension
        public: false
        tags:
            - { name: twig.extension }

