# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.registration_form_type:
        class: AppBundle\Form\Web\RegistrationFormType
        tags:
            - { name: form.type, alias: web_registration }

    app.profile_form_type:
        class: AppBundle\Form\Web\ProfileFormType
        tags:
            - { name: form.type, alias: web_profile }

    # -----------------
    # Admin Controllers
    # -----------------
    app.admin.user_controller:
        class: AppBundle\Controller\Admin\UserController
        arguments: ['@app.grid_data_source.admin.user_data_source', '@app.roles_provider', '@app.model.user_model']

    app.admin.static_text_controller:
        class: AppBundle\Controller\Admin\StaticTextController
        arguments:
            - '@app.grid_data_source.admin.static_text_data_source'
            - '@app.model.static_text_model'

    # -----------------
    # Web Controllers
    # -----------------

    app.web.homepage_controller:
        class: AppBundle\Controller\Web\HomePageController

    app.web.static_controller:
        class: AppBundle\Controller\Web\StaticController
        arguments: []

    app.web.profile_controller:
        class: AppBundle\Controller\Web\ProfileController

    # -----------------
    # Model
    # -----------------

    app.model.static_text_model:
        class: AppBundle\Model\StaticTextModel
        parent: 'app.model.abstract_logger_aware_model'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.repository.static_text_repository'

    app.model.user_model:
        class: AppBundle\Model\UserModel
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.repository.user_repository'
            - '@app.notifications.user_create_mail'

    # -----------------
    # IS Grid managers
    # -----------------
    app.grid_data_source.admin.static_text_data_source:
        class: AppBundle\GridDataSources\Admin\StaticTextDataSource
        arguments:
            - '@doctrine.orm.entity_manager'

    app.grid_data_source.admin.user_data_source:
        class: AppBundle\GridDataSources\Admin\UserDataSource
        arguments: ['@doctrine.orm.entity_manager']


    # ---------------------------
    # Repositories
    # ---------------------------
    app.repository.static_text_repository:
        class: AppBundle\Repository\StaticTextRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle:StaticText

    app.repository.user_repository:
        class: AppBundle\Repository\UserRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - AppBundle:User

    # ------------------------
    # Vich uploader extensions
    # ------------------------

    app.uploader.uniqid_namer:
        class: Vich\UploaderBundle\Naming\UniqidNamer


    # --------------------
    # Twig extensions
    # --------------------
    app.twig.static_text_extension:
        class: AppBundle\Twig\StaticTextExtension
        arguments:
            - '@app.model.static_text_model'
        tags:
            - { name: twig.extension }

