---
- name: Prepare symfony template server
  hosts: all
  sudo: true
  vars_files:
    - vars/project.yml
  roles:
      - designeo.server

- name: Deploy Local
  hosts: local
  vars_files:
      - vars/project.yml
      - vars/env/local.yml

- name: Deploy Production
  hosts: prod
  vars_files:
    - vars/project.yml
    - vars/env/prod.yml