---
#- name: push auth key
#  hosts:
#   - local
#  sudo: yes
#  tasks:
#   - name: auth key
#     authorized_key: user={{ansible_ssh_user}}
#                     key="{{ lookup('file', '/Users/johny/.ssh/johny.pub') }}"

- name: Prepare server
  hosts: all
  sudo: true
  vars_files:
    - vars/project.yml
  roles:
    - designeo.server
    - designeo.apache
    - designeo.php
    - kosssi.composer
    - designeo.postgresql
    - ateoto.nodejs

- name: Prepare server for php application
  hosts: all
  become: True
  vars_files:
    - vars/project.yml
  roles:
    - designeo.web_env

- name: Deploy symfony application
  hosts: all
  become: "{{ app_user }}"
  vars_files:
      - vars/project.yml
  roles:
    - designeo.symfony_app