---
- name: Deploy symfony template
  hosts: all
  sudo: true
  vars_files:
    - vars/symfony.yml
    - vars/project.yml
  roles:
    - designeo.server
    - galaxyprojectdotorg.postgresql
    - designeo.apache
    - designeo.php
    - kosssi.composer
    - ateoto.nodejs
    - designeo.symfony
