---
- name: push auth key
  hosts:
   - local
  sudo: yes
  tasks:
   - name: auth key
     authorized_key: user={{ansible_ssh_user}}
                     key="{{ lookup('file', '/Users/johny/.ssh/johny.pub') }}"

#- name: Install server and pgsql
#  hosts:
#   - local
#  sudo: yes
#  roles:
#   - designeo.server
#   - designeo.postgresql
##  tasks:
##   - name: Add ssh agent line to sudoers
##     lineinfile:
##       dest: /etc/sudoers
##       state: present
##       regexp: SSH_AUTH_SOCK
##       line: Defaults env_keep += "SSH_AUTH_SOCK"
##   - name: ssh test
##     command: ssh -T -oStrictHostKeyChecking=no git@github.com
#
#  vars_files:
#      - vars/symfony.yml
#      - vars/project.yml